modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "minersmarket"
version = "${version}"
displayName = "Miner's Market"
description = '''Compete to earn 10,000 gold by mining and selling ores!'''
authors = "ksoichiro"
displayURL = "https://github.com/ksoichiro/MinersMarket"

[[dependencies.minersmarket]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minersmarket]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.21.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minersmarket]]
modId = "architectury"
type = "required"
versionRange = "[15,)"
ordering = "AFTER"
side = "BOTH"
